### ISSUE TITLE
How to get  pin point

### ISSUE THREAD

**Issue by arishanapalli** [fortmarek/AnnotationETA#1]
Hi
Team,

I have integrated annotationETA in My Project. without pods.
with following files (AnnotationETA, DirectionButton, Directions, EtaAnnotation and EtaAnotationView.swift) and included the viewcontroller.swift

Pods increase the application size, so i am avoiding it, and directly using the swift classes into projects.

Issue:-
Every thing workings perfect, But not able to see pin point.
Inside the project i search for pinpoint (orange color) image unable to find too.

![img_1907](https://cloud.githubusercontent.com/assets/3903433/23460850/4eab0bca-fead-11e6-8b1b-d8ef2456156b.PNG)

**Comment by fortmarek** [comment]
Hey, 
Can I please see your implementation of func ```func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView?```

The reason you can not find any pin image is quite simple: there is not one. In EtaAnnotationView it is drawn using UIBezierPath.

**Comment by arishanapalli** [comment]
Hi
fortmarek,

Here the code used in the Viewcontroller.swift class.
And it is same as API example code.

```
    func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
        if annotation is MKUserLocation {return nil}
        var annotationView = MKAnnotationView()
        if let reusableAnnotationView = mapView.dequeueReusableAnnotationView(withIdentifier: "etaAnnotation") {
            annotationView = reusableAnnotationView
        }
        else {
            let annotationEtaView = EtaAnnotationView(annotation: annotation, reuseIdentifier: "etaAnnotation")
            annotationEtaView.pinColor = UIColor(red: 1.00, green: 0.50, blue: 0.00, alpha: 1.0)
            annotationEtaView.setDetailShowButton()
            annotationEtaView.rightButton?.addTarget(self, action: #selector(detailButtonTapped), for: .touchUpInside)
            annotationView = annotationEtaView
        }
        return annotationView
    }
```


Thanks You!
A Kiran Kumar

**Comment by fortmarek** [comment]
I tried implementing it just by importing the files and it worked with no problem. You can see the implementation here: https://github.com/fortmarek/AnnotationETATest 
Try to compare it with your code (for example, check if the AnnotationETA files are the same, etc.)

**Comment by arishanapalli** [comment]
@fortmarek 
Thank you!
Its work fine now.
I got the annotation pin after replacing those files.

??????
Can i use your class files for commercial purposes?

**Comment by fortmarek** [comment]
Yes, the repository is under the MIT license, so you can use all of the code freely.

**Comment by arishanapalli** [comment]
Thank You fortmarek!
